CREATE TABLE IF NOT EXISTS `data_post` (
    `id`                 INT           UNSIGNED NOT NULL AUTO_INCREMENT,
    `hash`               CHAR(31)      NOT NULL,
    `p_data_timestamp`   INT(10)       UNSIGNED NOT NULL,
    `flight_no`          VARCHAR(4)    NOT NULL,
    `origin`             VARCHAR(3)    NOT NULL,
    `destination`        VARCHAR(3)    NOT NULL,
    `date`               DATE          NOT NULL,
    `day_of_week`        TINYINT       NOT NULL,
    `actual_flight_time` VARCHAR(10)   NOT NULL,
    `p_ca_bu`            SMALLINT      NOT NULL,
    `p_ca_co`            SMALLINT      NOT NULL,
    `p_ca_pp`            SMALLINT      NOT NULL,
    `p_ca_to`            SMALLINT      NOT NULL,
    `p_au_bu`            SMALLINT      NOT NULL,
    `p_au_co`            SMALLINT      NOT NULL,
    `p_au_pp`            SMALLINT      NOT NULL,
    `p_au_to`            SMALLINT      NOT NULL,
    `p_bo_bu`            SMALLINT      NOT NULL,
    `p_bo_co`            SMALLINT      NOT NULL,
    `p_bo_pp`            SMALLINT      NOT NULL,
    `p_bo_to`            SMALLINT      NOT NULL,
    `p_ps_bu`            SMALLINT      NOT NULL,
    `p_ps_co`            SMALLINT      NOT NULL,
    `p_ps_pp`            SMALLINT      NOT NULL,
    `p_ps_to`            SMALLINT      NOT NULL,
    `p_sa_bu`            SMALLINT      NOT NULL,
    `p_sa_co`            SMALLINT      NOT NULL,
    `p_sa_pp`            SMALLINT      NOT NULL,
    `p_sa_to`            SMALLINT      NOT NULL,
    `p_he_bu`            SMALLINT      NOT NULL,
    `p_he_co`            SMALLINT      NOT NULL,
    `p_he_pp`            SMALLINT      NOT NULL,
    `p_he_to`            SMALLINT      NOT NULL,
    `p_gr_bu`            SMALLINT      NOT NULL,
    `p_gr_co`            SMALLINT      NOT NULL,
    `p_gr_pp`            SMALLINT      NOT NULL,
    `p_gr_to`            SMALLINT      NOT NULL,
    `p_re_bu`            SMALLINT      NOT NULL,
    `p_re_co`            SMALLINT      NOT NULL,
    `p_re_pp`            SMALLINT      NOT NULL,
    `p_re_to`            SMALLINT      NOT NULL,
    `p_ci_bu`            SMALLINT      NOT NULL,
    `p_ci_co`            SMALLINT      NOT NULL,
    `p_ci_pp`            SMALLINT      NOT NULL,
    `p_ci_to`            SMALLINT      NOT NULL,
    `p_cl_ug_bu`         SMALLINT      NOT NULL,
    `p_cl_ug_co`         SMALLINT      NOT NULL,
    `p_cl_ug_pp`         SMALLINT      NOT NULL,
    `p_cl_sa_bu`         SMALLINT      NOT NULL,
    `p_cl_sa_co`         SMALLINT      NOT NULL,
    `p_cl_sa_pp`         SMALLINT      NOT NULL,
    `p_cl_to_bu`         SMALLINT      NOT NULL,
    `p_cl_to_co`         SMALLINT      NOT NULL,
    `p_cl_to_pp`         SMALLINT      NOT NULL,
    `p_sy_ug_bu`         SMALLINT      NOT NULL,
    `p_sy_ug_co`         SMALLINT      NOT NULL,
    `p_sy_ug_pp`         SMALLINT      NOT NULL,
    `p_sy_sa_bu`         SMALLINT      NOT NULL,
    `p_sy_sa_co`         SMALLINT      NOT NULL,
    `p_sy_sa_pp`         SMALLINT      NOT NULL,
    `p_sy_to_bu`         SMALLINT      NOT NULL,
    `p_sy_to_co`         SMALLINT      NOT NULL,
    `p_sy_to_pp`         SMALLINT      NOT NULL,
    `p_data_raw`         JSON          NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY (`hash`)
);