CREATE TABLE IF NOT EXISTS `data` (
    `id`                 INT           UNSIGNED NOT NULL AUTO_INCREMENT,
    `hash`               CHAR(31)      NOT NULL,
    `data_timestamp`     INT(10)       UNSIGNED NOT NULL,
    `flight_no`          VARCHAR(4)    NOT NULL,
    `origin`             VARCHAR(3)    NOT NULL,
    `destination`        VARCHAR(3)    NOT NULL,
    `date`               DATE          NOT NULL,
    `day_of_week`        TINYINT       NOT NULL,
    `flight_time`        VARCHAR(10)   NOT NULL,
    `av_bu`              SMALLINT      NOT NULL,
    `av_co`              SMALLINT      NOT NULL,
    `av_pp`              SMALLINT      NOT NULL,
    `av_to`              SMALLINT      NOT NULL,
    `ca_bu`              SMALLINT      NOT NULL,
    `ca_co`              SMALLINT      NOT NULL,
    `ca_pp`              SMALLINT      NOT NULL,
    `ca_to`              SMALLINT      NOT NULL,
    `au_bu`              SMALLINT      NOT NULL,
    `au_co`              SMALLINT      NOT NULL,
    `au_pp`              SMALLINT      NOT NULL,
    `au_to`              SMALLINT      NOT NULL,
    `bo_bu`              SMALLINT      NOT NULL,
    `bo_co`              SMALLINT      NOT NULL,
    `bo_pp`              SMALLINT      NOT NULL,
    `bo_to`              SMALLINT      NOT NULL,
    `ps_bu`              SMALLINT      NOT NULL,
    `ps_co`              SMALLINT      NOT NULL,
    `ps_pp`              SMALLINT      NOT NULL,
    `ps_to`              SMALLINT      NOT NULL,
    `sa_bu`              SMALLINT      NOT NULL,
    `sa_co`              SMALLINT      NOT NULL,
    `sa_pp`              SMALLINT      NOT NULL,
    `sa_to`              SMALLINT      NOT NULL,
    `he_bu`              SMALLINT      NOT NULL,
    `he_co`              SMALLINT      NOT NULL,
    `he_pp`              SMALLINT      NOT NULL,
    `he_to`              SMALLINT      NOT NULL,
    `gr_bu`              SMALLINT      NOT NULL,
    `gr_co`              SMALLINT      NOT NULL,
    `gr_pp`              SMALLINT      NOT NULL,
    `gr_to`              SMALLINT      NOT NULL,
    `re_bu`              SMALLINT      NOT NULL,
    `re_co`              SMALLINT      NOT NULL,
    `re_pp`              SMALLINT      NOT NULL,
    `re_to`              SMALLINT      NOT NULL,
    `pos_va`             SMALLINT      NOT NULL,
    `pos_pe`             SMALLINT      NOT NULL,
    `flight_raw`         JSON          NOT NULL,
    `pass_rider_raw`     JSON          NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY (`hash`)
);